killbill/killbill-oss-parent

- pom.xml
noticed the changelog mentioned a slight performance regression in 1.1.8
relevant issue: https://mariadb.atlassian.net/browse/CONJ-151
> update mariadb-java-client to 1.1.9

- pom.xml
Related to https://github.com/killbill/killbill-platform/pull/31
> Add dependency on jasypt

- pom.xml
> Swagger UI upgrade

- NEWS
- pom.xml
This also add Redis dependencies for future use... 😇
> Jdk8 upgrade

- NEWS
- pom.xml
This improves overall performance, see https://github.com/redisson/redisson/commit/a89f1a7f25549e7aa8e4154ff5230ac15dce6ddf.
> pom.xml: update Redisson to 3.10.0

- NEWS
- pom.xml
This addresses wave 3 of killbill/killbill-oss-parent#34.
> Update Jersey from 1.19.4 to 2.32

- .github/workflows/ci.yml
- NEWS
- pom.xml
This fixes https://github.com/killbill/killbill-oss-parent/issues/176.
> pom.xml: update manifold to 2021.1.11

- NEWS
- pom.xml
CI won't work as this requires Kill Bill changes.
> pom.xml: update shiro to 1.8.0

- pom.xml
See https://github.com/killbill/killbill-commons/pull/121.
> pom.xml: remove spring dependencies

- pom.xml
This is part of https://github.com/killbill/killbill/issues/1640.
> pom.xml: remove AsyncHttpClient dependency

- pom.xml
Lets solve the issue one by one:
1. This one for `returning()` problem.
2. After that, lets step in and decide about this issue: https://github.com/killbill/killbill-oss-parent/issues/552
> downgrade jooq version

- pom.xml
Original issue: https://github.com/killbill/technical-support/issues/57 . 
Testing approach: https://github.com/killbill/technical-support/issues/57#issuecomment-1262748291
> update shiro version to 1.9.1

- pom.xml
Related issue: https://github.com/killbill/technical-support/issues/57
> update jackson-databind and snakeyaml version

- pom.xml
See https://github.com/killbill/killbill-oss-parent/issues/552#issuecomment-1276752397, point A.1
> add embedded-postgres dependency and parameterize jooq version

- pom.xml
make derby and derbytool have the same version.
related PR: https://github.com/killbill/killbill-oss-parent/pull/611
> make derby and derbytool have the same version

- .github/workflows/ci.yml
- pom.xml
> update org.osgi.service.log to 1.5.0, and remove testing-mysql-server

- .github/workflows/ci.yml
apply to:
- plugin-framework
- platform
- client-java
- killbill
> update refs/heads/work-for-release-0.23.x to refs/heads/master

- pom.xml
- Updated `snappy-java` to `1.1.10.4`
- Excluded `protobuf` dependency
- Updated logback to `1.3.14` and `slf4j` to `2.0.7`
> Work for ts 126

- pom.xml
Update killbill-plugin-api to version `0.27.3` for https://github.com/killbill/killbill/issues/1841
> Update killbill-plugin-api to version 0.27.3 for 1841

- .github/workflows/snapshot.yml
- pom.xml
https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh
SNAPSHOT is working: https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/org/kill-bill/billing/killbill-oss-parent/
> OSSRH Migration
